export enum OrderStatuses {
  CONFIRMING_PAYMENT = 'ors-001',
  PAYMENT_ACCEPTED = 'ors-002',
  PAYMENT_REJECTED = 'ors-003',
  SENDING_PRODUCTS = 'ors-004',
  PRODUCTS_SENT = 'ors-005',
  SHIPPING_ERROR = 'ors-006',
  PRODUCTS_RECEIVED = 'ors-007',
  WAITING_FOR_PICKUP_AT_STORE = 'ors-008',
}
